CREATE TABLE _attributes (
	timestamp DATETIME, 
	"key" VARCHAR NOT NULL, 
	value VARCHAR, 
	PRIMARY KEY ("key")
);
CREATE TABLE summary (
	timestamp DATETIME, 
	"key" VARCHAR NOT NULL, 
	value VARCHAR, 
	PRIMARY KEY ("key")
);
CREATE TABLE years_summary (
	first_day DATE NOT NULL, 
	hr_avg FLOAT, 
	hr_min FLOAT, 
	hr_max FLOAT, 
	rhr_avg FLOAT, 
	rhr_min FLOAT, 
	rhr_max FLOAT, 
	inactive_hr_avg FLOAT, 
	inactive_hr_min FLOAT, 
	inactive_hr_max FLOAT, 
	weight_avg FLOAT, 
	weight_min FLOAT, 
	weight_max FLOAT, 
	intensity_time TIME NOT NULL, 
	moderate_activity_time TIME NOT NULL, 
	vigorous_activity_time TIME NOT NULL, 
	intensity_time_goal TIME NOT NULL, 
	steps INTEGER, 
	steps_goal INTEGER, 
	floors FLOAT, 
	floors_goal FLOAT, 
	sleep_avg TIME NOT NULL, 
	sleep_min TIME NOT NULL, 
	sleep_max TIME NOT NULL, 
	rem_sleep_avg TIME NOT NULL, 
	rem_sleep_min TIME NOT NULL, 
	rem_sleep_max TIME NOT NULL, 
	stress_avg INTEGER, 
	calories_avg INTEGER, 
	calories_bmr_avg INTEGER, 
	calories_active_avg INTEGER, 
	calories_goal INTEGER, 
	calories_consumed_avg INTEGER, 
	activities INTEGER, 
	activities_calories INTEGER, 
	activities_distance INTEGER, 
	hydration_goal INTEGER, 
	hydration_avg INTEGER, 
	hydration_intake INTEGER, 
	sweat_loss_avg INTEGER, 
	sweat_loss INTEGER, 
	spo2_avg FLOAT, 
	spo2_min FLOAT, 
	rr_waking_avg FLOAT, 
	rr_max FLOAT, 
	rr_min FLOAT, 
	bb_max INTEGER, 
	bb_min INTEGER, 
	PRIMARY KEY (first_day)
);
CREATE TABLE months_summary (
	first_day DATE NOT NULL, 
	hr_avg FLOAT, 
	hr_min FLOAT, 
	hr_max FLOAT, 
	rhr_avg FLOAT, 
	rhr_min FLOAT, 
	rhr_max FLOAT, 
	inactive_hr_avg FLOAT, 
	inactive_hr_min FLOAT, 
	inactive_hr_max FLOAT, 
	weight_avg FLOAT, 
	weight_min FLOAT, 
	weight_max FLOAT, 
	intensity_time TIME NOT NULL, 
	moderate_activity_time TIME NOT NULL, 
	vigorous_activity_time TIME NOT NULL, 
	intensity_time_goal TIME NOT NULL, 
	steps INTEGER, 
	steps_goal INTEGER, 
	floors FLOAT, 
	floors_goal FLOAT, 
	sleep_avg TIME NOT NULL, 
	sleep_min TIME NOT NULL, 
	sleep_max TIME NOT NULL, 
	rem_sleep_avg TIME NOT NULL, 
	rem_sleep_min TIME NOT NULL, 
	rem_sleep_max TIME NOT NULL, 
	stress_avg INTEGER, 
	calories_avg INTEGER, 
	calories_bmr_avg INTEGER, 
	calories_active_avg INTEGER, 
	calories_goal INTEGER, 
	calories_consumed_avg INTEGER, 
	activities INTEGER, 
	activities_calories INTEGER, 
	activities_distance INTEGER, 
	hydration_goal INTEGER, 
	hydration_avg INTEGER, 
	hydration_intake INTEGER, 
	sweat_loss_avg INTEGER, 
	sweat_loss INTEGER, 
	spo2_avg FLOAT, 
	spo2_min FLOAT, 
	rr_waking_avg FLOAT, 
	rr_max FLOAT, 
	rr_min FLOAT, 
	bb_max INTEGER, 
	bb_min INTEGER, 
	PRIMARY KEY (first_day)
);
CREATE TABLE weeks_summary (
	first_day DATE NOT NULL, 
	hr_avg FLOAT, 
	hr_min FLOAT, 
	hr_max FLOAT, 
	rhr_avg FLOAT, 
	rhr_min FLOAT, 
	rhr_max FLOAT, 
	inactive_hr_avg FLOAT, 
	inactive_hr_min FLOAT, 
	inactive_hr_max FLOAT, 
	weight_avg FLOAT, 
	weight_min FLOAT, 
	weight_max FLOAT, 
	intensity_time TIME NOT NULL, 
	moderate_activity_time TIME NOT NULL, 
	vigorous_activity_time TIME NOT NULL, 
	intensity_time_goal TIME NOT NULL, 
	steps INTEGER, 
	steps_goal INTEGER, 
	floors FLOAT, 
	floors_goal FLOAT, 
	sleep_avg TIME NOT NULL, 
	sleep_min TIME NOT NULL, 
	sleep_max TIME NOT NULL, 
	rem_sleep_avg TIME NOT NULL, 
	rem_sleep_min TIME NOT NULL, 
	rem_sleep_max TIME NOT NULL, 
	stress_avg INTEGER, 
	calories_avg INTEGER, 
	calories_bmr_avg INTEGER, 
	calories_active_avg INTEGER, 
	calories_goal INTEGER, 
	calories_consumed_avg INTEGER, 
	activities INTEGER, 
	activities_calories INTEGER, 
	activities_distance INTEGER, 
	hydration_goal INTEGER, 
	hydration_avg INTEGER, 
	hydration_intake INTEGER, 
	sweat_loss_avg INTEGER, 
	sweat_loss INTEGER, 
	spo2_avg FLOAT, 
	spo2_min FLOAT, 
	rr_waking_avg FLOAT, 
	rr_max FLOAT, 
	rr_min FLOAT, 
	bb_max INTEGER, 
	bb_min INTEGER, 
	PRIMARY KEY (first_day)
);
CREATE TABLE days_summary (
	day DATE NOT NULL, 
	hr_avg FLOAT, 
	hr_min FLOAT, 
	hr_max FLOAT, 
	rhr_avg FLOAT, 
	rhr_min FLOAT, 
	rhr_max FLOAT, 
	inactive_hr_avg FLOAT, 
	inactive_hr_min FLOAT, 
	inactive_hr_max FLOAT, 
	weight_avg FLOAT, 
	weight_min FLOAT, 
	weight_max FLOAT, 
	intensity_time TIME NOT NULL, 
	moderate_activity_time TIME NOT NULL, 
	vigorous_activity_time TIME NOT NULL, 
	intensity_time_goal TIME NOT NULL, 
	steps INTEGER, 
	steps_goal INTEGER, 
	floors FLOAT, 
	floors_goal FLOAT, 
	sleep_avg TIME NOT NULL, 
	sleep_min TIME NOT NULL, 
	sleep_max TIME NOT NULL, 
	rem_sleep_avg TIME NOT NULL, 
	rem_sleep_min TIME NOT NULL, 
	rem_sleep_max TIME NOT NULL, 
	stress_avg INTEGER, 
	calories_avg INTEGER, 
	calories_bmr_avg INTEGER, 
	calories_active_avg INTEGER, 
	calories_goal INTEGER, 
	calories_consumed_avg INTEGER, 
	activities INTEGER, 
	activities_calories INTEGER, 
	activities_distance INTEGER, 
	hydration_goal INTEGER, 
	hydration_avg INTEGER, 
	hydration_intake INTEGER, 
	sweat_loss_avg INTEGER, 
	sweat_loss INTEGER, 
	spo2_avg FLOAT, 
	spo2_min FLOAT, 
	rr_waking_avg FLOAT, 
	rr_max FLOAT, 
	rr_min FLOAT, 
	bb_max INTEGER, 
	bb_min INTEGER, 
	PRIMARY KEY (day)
);
CREATE TABLE intensity_hr (
	timestamp DATETIME NOT NULL, 
	intensity INTEGER NOT NULL, 
	heart_rate INTEGER NOT NULL, 
	PRIMARY KEY (timestamp)
);
CREATE VIEW years_summary_view AS SELECT years_summary.first_day AS first_day, ROUND(years_summary.rhr_avg, 1) AS rhr , ROUND(years_summary.inactive_hr_avg, 1) AS inactive_hr , ROUND(years_summary.weight_avg, 1) AS weight , years_summary.intensity_time AS intensity_time, years_summary.moderate_activity_time AS moderate_activity_time, years_summary.vigorous_activity_time AS vigorous_activity_time, years_summary.steps AS total_steps, ROUND(round(steps / 365), 1) AS steps_avg , ROUND(round((steps * 100) / steps_goal), 1) AS steps_goal_percent , ROUND(floors, 1) AS total_floors , ROUND(round(floors / 365), 1) AS floors_avg , ROUND(round((floors * 100) / floors_goal), 1) AS floors_goal_percent , years_summary.sleep_avg AS sleep_avg, years_summary.rem_sleep_avg AS rem_sleep_avg, ROUND(years_summary.stress_avg, 1) AS stress_avg , ROUND(years_summary.calories_avg, 1) AS calories_avg , ROUND(years_summary.calories_bmr_avg, 1) AS calories_bmr_avg , ROUND(years_summary.calories_active_avg, 1) AS calories_active_avg , ROUND(years_summary.calories_consumed_avg, 1) AS calories_consumed_avg , ROUND(years_summary.calories_goal, 1) AS calories_goal , years_summary.activities AS activities, ROUND(years_summary.activities_calories, 1) AS activities_calories , ROUND(years_summary.activities_distance, 1) AS activities_distance , ROUND(years_summary.hydration_goal, 1) AS hydration_goal , ROUND(years_summary.hydration_avg, 1) AS hydration_avg , ROUND(years_summary.sweat_loss_avg, 1) AS sweat_loss_avg , ROUND(years_summary.sweat_loss_avg, 1) AS sweat_loss_avg , ROUND(years_summary.spo2_avg, 1) AS spo2_avg , ROUND(years_summary.rr_waking_avg, 1) AS rr_waking_avg  
FROM years_summary ORDER BY years_summary.first_day DESC
/* years_summary_view(first_day,rhr,inactive_hr,weight,intensity_time,moderate_activity_time,vigorous_activity_time,total_steps,steps_avg,steps_goal_percent,total_floors,floors_avg,floors_goal_percent,sleep_avg,rem_sleep_avg,stress_avg,calories_avg,calories_bmr_avg,calories_active_avg,calories_consumed_avg,calories_goal,activities,activities_calories,activities_distance,hydration_goal,hydration_avg,sweat_loss_avg,"sweat_loss_avg:1",spo2_avg,rr_waking_avg) */;
CREATE VIEW months_summary_view AS SELECT months_summary.first_day AS first_day, ROUND(months_summary.rhr_avg, 1) AS rhr , ROUND(months_summary.inactive_hr_avg, 1) AS inactive_hr , ROUND(months_summary.weight_avg, 1) AS weight , months_summary.intensity_time AS intensity_time, months_summary.moderate_activity_time AS moderate_activity_time, months_summary.vigorous_activity_time AS vigorous_activity_time, months_summary.steps AS total_steps, ROUND(round(steps / 28), 1) AS steps_avg , ROUND(round((steps * 100) / steps_goal), 1) AS steps_goal_percent , ROUND(floors, 1) AS total_floors , ROUND(round(floors / 28), 1) AS floors_avg , ROUND(round((floors * 100) / floors_goal), 1) AS floors_goal_percent , months_summary.sleep_avg AS sleep_avg, months_summary.rem_sleep_avg AS rem_sleep_avg, ROUND(months_summary.stress_avg, 1) AS stress_avg , ROUND(months_summary.calories_avg, 1) AS calories_avg , ROUND(months_summary.calories_bmr_avg, 1) AS calories_bmr_avg , ROUND(months_summary.calories_active_avg, 1) AS calories_active_avg , ROUND(months_summary.calories_consumed_avg, 1) AS calories_consumed_avg , ROUND(months_summary.calories_goal, 1) AS calories_goal , months_summary.activities AS activities, ROUND(months_summary.activities_calories, 1) AS activities_calories , ROUND(months_summary.activities_distance, 1) AS activities_distance , ROUND(months_summary.hydration_goal, 1) AS hydration_goal , ROUND(months_summary.hydration_avg, 1) AS hydration_avg , ROUND(months_summary.sweat_loss_avg, 1) AS sweat_loss_avg , ROUND(months_summary.sweat_loss_avg, 1) AS sweat_loss_avg , ROUND(months_summary.spo2_avg, 1) AS spo2_avg , ROUND(months_summary.rr_waking_avg, 1) AS rr_waking_avg  
FROM months_summary ORDER BY months_summary.first_day DESC
/* months_summary_view(first_day,rhr,inactive_hr,weight,intensity_time,moderate_activity_time,vigorous_activity_time,total_steps,steps_avg,steps_goal_percent,total_floors,floors_avg,floors_goal_percent,sleep_avg,rem_sleep_avg,stress_avg,calories_avg,calories_bmr_avg,calories_active_avg,calories_consumed_avg,calories_goal,activities,activities_calories,activities_distance,hydration_goal,hydration_avg,sweat_loss_avg,"sweat_loss_avg:1",spo2_avg,rr_waking_avg) */;
CREATE VIEW weeks_summary_view AS SELECT weeks_summary.first_day AS first_day, ROUND(weeks_summary.rhr_avg, 1) AS rhr , ROUND(weeks_summary.inactive_hr_avg, 1) AS inactive_hr , ROUND(weeks_summary.weight_avg, 1) AS weight , weeks_summary.intensity_time AS intensity_time, weeks_summary.moderate_activity_time AS moderate_activity_time, weeks_summary.vigorous_activity_time AS vigorous_activity_time, weeks_summary.steps AS total_steps, ROUND(round(steps / 7), 1) AS steps_avg , ROUND(round((steps * 100) / steps_goal), 1) AS steps_goal_percent , ROUND(floors, 1) AS total_floors , ROUND(round(floors / 7), 1) AS floors_avg , ROUND(round((floors * 100) / floors_goal), 1) AS floors_goal_percent , weeks_summary.sleep_avg AS sleep_avg, weeks_summary.rem_sleep_avg AS rem_sleep_avg, ROUND(weeks_summary.stress_avg, 1) AS stress_avg , ROUND(weeks_summary.calories_avg, 1) AS calories_avg , ROUND(weeks_summary.calories_bmr_avg, 1) AS calories_bmr_avg , ROUND(weeks_summary.calories_active_avg, 1) AS calories_active_avg , ROUND(weeks_summary.calories_consumed_avg, 1) AS calories_consumed_avg , ROUND(weeks_summary.calories_goal, 1) AS calories_goal , weeks_summary.activities AS activities, ROUND(weeks_summary.activities_calories, 1) AS activities_calories , ROUND(weeks_summary.activities_distance, 1) AS activities_distance , ROUND(weeks_summary.hydration_goal, 1) AS hydration_goal , ROUND(weeks_summary.hydration_avg, 1) AS hydration_avg , ROUND(weeks_summary.sweat_loss_avg, 1) AS sweat_loss_avg , ROUND(weeks_summary.sweat_loss_avg, 1) AS sweat_loss_avg , ROUND(weeks_summary.spo2_avg, 1) AS spo2_avg , ROUND(weeks_summary.rr_waking_avg, 1) AS rr_waking_avg  
FROM weeks_summary ORDER BY weeks_summary.first_day DESC
/* weeks_summary_view(first_day,rhr,inactive_hr,weight,intensity_time,moderate_activity_time,vigorous_activity_time,total_steps,steps_avg,steps_goal_percent,total_floors,floors_avg,floors_goal_percent,sleep_avg,rem_sleep_avg,stress_avg,calories_avg,calories_bmr_avg,calories_active_avg,calories_consumed_avg,calories_goal,activities,activities_calories,activities_distance,hydration_goal,hydration_avg,sweat_loss_avg,"sweat_loss_avg:1",spo2_avg,rr_waking_avg) */;
CREATE VIEW days_summary_view AS SELECT days_summary.day AS day, ROUND(days_summary.hr_avg, 1) AS hr_avg , ROUND(days_summary.hr_min, 1) AS hr_min , ROUND(days_summary.hr_max, 1) AS hr_max , ROUND(days_summary.rhr_avg, 1) AS rhr , ROUND(days_summary.inactive_hr_avg, 1) AS inactive_hr , ROUND(days_summary.weight_avg, 1) AS weight , days_summary.intensity_time AS intensity_time, days_summary.moderate_activity_time AS moderate_activity_time, days_summary.vigorous_activity_time AS vigorous_activity_time, days_summary.steps AS steps, ROUND(round((steps * 100) / steps_goal), 1) AS steps_goal_percent , ROUND(days_summary.floors, 1) AS floors , ROUND(round((floors * 100) / floors_goal), 1) AS floors_goal_percent , days_summary.sleep_avg AS sleep_avg, days_summary.rem_sleep_avg AS rem_sleep_avg, ROUND(days_summary.stress_avg, 1) AS stress_avg , ROUND(days_summary.calories_avg, 1) AS calories_avg , ROUND(days_summary.calories_bmr_avg, 1) AS calories_bmr_avg , ROUND(days_summary.calories_active_avg, 1) AS calories_active_avg , ROUND(days_summary.calories_consumed_avg, 1) AS calories_consumed_avg , ROUND(days_summary.calories_goal, 1) AS calories_goal , days_summary.activities AS activities, ROUND(days_summary.activities_calories, 1) AS activities_calories , ROUND(days_summary.activities_distance, 1) AS activities_distance , ROUND(days_summary.hydration_goal, 1) AS hydration_goal , ROUND(days_summary.hydration_avg, 1) AS hydration_avg , ROUND(days_summary.sweat_loss_avg, 1) AS sweat_loss_avg , ROUND(days_summary.spo2_avg, 1) AS spo2_avg , ROUND(days_summary.spo2_min, 1) AS spo2_min , ROUND(days_summary.rr_waking_avg, 1) AS rr_waking_avg , ROUND(days_summary.rr_max, 1) AS rr_max , ROUND(days_summary.rr_min, 1) AS rr_min , ROUND(days_summary.bb_max, 1) AS bb_max , ROUND(days_summary.bb_min, 1) AS bb_min  
FROM days_summary ORDER BY days_summary.day DESC
/* days_summary_view(day,hr_avg,hr_min,hr_max,rhr,inactive_hr,weight,intensity_time,moderate_activity_time,vigorous_activity_time,steps,steps_goal_percent,floors,floors_goal_percent,sleep_avg,rem_sleep_avg,stress_avg,calories_avg,calories_bmr_avg,calories_active_avg,calories_consumed_avg,calories_goal,activities,activities_calories,activities_distance,hydration_goal,hydration_avg,sweat_loss_avg,spo2_avg,spo2_min,rr_waking_avg,rr_max,rr_min,bb_max,bb_min) */;
